const GAME_STATE_WAITING = 1;
const GAME_STATE_STARTED = 2;
const GAME_STATE_CHOOSING_WORD = 3;
const GAME_STATE_DRAWING = 4;
const GAME_STATE_END = 5;

export const state = {
  GAME_STATE_CHOOSING_WORD,
  GAME_STATE_DRAWING,
  GAME_STATE_STARTED,
  GAME_STATE_WAITING,
  GAME_STATE_END,
};
